### PR TITLE
Alter i_size column to BIGINT in images table

### LINKED ISSUE #157: PostgreSQL ERROR: integer out of range (i_size field for big layers)
```
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]: ERROR [qtp1145411169-3299] [PATCH /v2/qu/apache-atlas/blobs/uploads/7ed492ab-442e-4a9f-9f7f-865f7beb9a5a <- 18.184.51.186, 18.196.34.121] i.s.s.parser - internal server error java.sql.BatchUpdateException: Batch entry 0 INSERT INTO images
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]:        (i_id, i_metadata, i_accepted, i_parent_id, i_size, i_created_by)
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]: VALUES ('sha256:814262eaac6b343988c1cd675af3771b0292cbf455a9e524ea8703f7e19e6e8b', '', FALSE, NULL, 3597196812, 'credprov-cdp-controller-proxy_pierone-token') was aborted: ERROR: integer out of range  Call getNextException to see the cause.
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO images
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]:        (i_id, i_metadata, i_accepted, i_parent_id, i_size, i_created_by)
18:56:28.317 pierone /var/log/application.log May  8 16:56:25 ip-172-31-164-88 docker/8d0d306616bd[873]: VALUES ('sha256:814262eaac6b343988c1cd675af3771b0292cbf455a9e524ea8703f7e19e6e8b', '', FALSE, NULL, 3597196812, 'credprov-cdp-controller-proxy_pierone-token') was aborted: ERROR: integer out of range  Call getNextException to see the cause.
```

Apparently the integer type for the layer size (`i_size` column) is not enough for big layers :laughing:

### PR DESCRIPTION
**Pull request by lotharschulz**
fix: #157

Alters column `zp_data.images.i_size` to BIGINT ( including `USING` ). 

[Modifying Tables postgres tables](https://www.postgresql.org/docs/9.4/static/ddl-alter.html) mentions :

> This will succeed only if each existing entry in the column can be converted to the new type by an implicit cast. If a more complex conversion is needed, you can add a USING clause that specifies how to compute the new values from the old.

See also [postgresql change column type](http://www.postgresqltutorial.com/postgresql-change-column-type/).

I am not sure if **INT** -> **BIGINT** conversion is complex, however the PR uses `USING` because I did not find resources reporting `USING` hurts.

If approved, the migration run should be scheduled with respect to customer usage.

### CODE REVIEW

File: resources/db/migration/V2__Add_image_size.sql [hunk 1]
```diff
@@ -1,4 +1,4 @@
 -- store image size on upload
--- to not touch files when someone requests stats
+-- do not touch files when someone requests stats
```
Comment (hjacobs) [inline resources/db/migration/V2__Add_image_size.sql]: I think "to" was correct here --- "store image size on upload to ..."

Comment (dryewo) [inline resources/db/migration/V2__Add_image_size.sql]: Please revert changes in this file.
One should not edit existing migrations, they are checked with checksum on app start.
If we merge this and deploy, the application will throw an exception and reject to start.

**Comment by lotharschulz** [comment]
👍

**Comment by dryewo** [comment]
I just tried this on my machine with full production data, migration took ~30s. Should be no problem.

**Comment by dryewo** [comment]
:+1:

**Comment by lotharschulz** [comment]
Double checked with database team and @dryewo and agreed that before rollout I should create backup table:

```
CREATE TABLE zp_data.images_backup AS
  TABLE zp_data.images;
```
(outside of this PR).

Will leave the PR also open until the roll out is scheduled and performed.

**Comment by lotharschulz** [comment]
@dryewo did run 

```
CREATE TABLE zp_data.images_backup AS
  TABLE zp_data.images;
```

on his local dump that took 16 seconds .
